HackYourFuture/databases

Lesson1.md

Removed stale YouTube links in favor of a Lynda playlist.

Updated pre-class readings in Lesson1

---

Lesson1.md
Lesson2.md
Lesson3.md

Removed a confusing link from Lesson1.md
Updated list of videos in Lesson2.md and Lesson3.md to use Lynda.com links.

Feedback changes and Playlist Updates

---

Week1/README.md

datatypes into readme

---

README.md

The _ wildcard did not work as expected during the class in the sense that the command would execute successfully but user hyfuser will have no permissions to anything after.

Replace wildcard _ by * for windows compatibility

---

Week1/MAKEME.md

- Make sure the file more than once (drop database and use database required at the beginning of the file)
- Encourage them to use a database viewer and to check their data
- 5 of each table is enough
- In Part 1 we ask to create EmployeeS ProjectS and DepartmentS but in part2 , singular is used Country, City.. Use the singular one

Homework 1 review

---

Week1/big-data.js

Here is a js file that fills up a simple db with same value in both columns but on with a PK and so Index and one without.
You can separate the insert and the query so if you want you can load it before the class but it's not that long on my computer.
the result is pretty clear :
Execution time with a primary key: 4ms
Execution time with no index: 10678ms

js file to fill up big db

---

Week3/README.md

One important rule for 1NF was missing. Added this to the quick explanation that was already provided for 1NF

Adds a missing rule for 1NF in Week3 README

---

Week1/big-data.js
Week2/LESSONPLAN.md

- Fixed a typo in one query.
- Wrote the answer query to one of the exercises.
- Reduce the number of inserts from 10M to 1M for big-data demonstrating query

write queries in lesson plan

---

Week2/MAKEME.md
Week2/README.md

I've added meaningful commit titles to explain what had to be improved

Improve week 2

---

Week3/MAKEME.md
Week3/README.md

just some minor improvements, mostly just formatting and typos

formatting improvements

---

Week3/MAKEME.md

I think we should not focus on the exact normalization steps in the exercise.
The goal however seems legit, so I propose to keep the exercise but stress less about the normal forms.

change focus from normalization exercises

---

Week2/MAKEME.md

This change is to address this issue:
https://github.com/HackYourHomework/databases-1/pull/15#discussion_r551800358
In the old situation the relation could be interpreted at 1-to-many and many-to-many.

change the week2 exercise

---

Week3/MAKEME.md
Week3/README.md

my attempt to address the comments from students
>>>
- mongodb explanation was lacking - there should be a video how to work with it
two guys said we should include this video: https://www.youtube.com/watch?v=-56x56UppqQ
- MongoDB makeMe exercise is partly in the readme.

make changes to mongo explanation and exercise

---

Week1/README.md

This video is talking about persisting vs non-persisting data and how to configure it using mendix software.
It's more confusing than educational.

remove mendix video

---

Week3/README.md

it's either `BEGIN` or `START TRANSACTION`

Fix syntax error: begin transaction

---

README.md

If students don't set this option they can't run any scripts that use the  `mysql` npm package

installation instruction

---

Week2/README.md

The first link is not public anymore, found an alternative

Replace dead link

---

Week1/QA_PREP_EXERCISE.md

Hey folks,
These are the potential exercises for Q&A prep for week 1. The idea is simple: get the students to think about databases a little beyond what they just practiced during the homework. At this point, the students don't understand the concept of relationships between tables, so this exercise will be challenging and requires some outside research for those who want to solve it. The following week, they go deep into relationships; having already attempted to build relationships will better help them cement that understanding as they will connect the dots with this exercise.
The expectation is that many of them won't be able to solve it or will come up with non-suitable designs, but that's fine as we will cover a good design during the Q&A.
Lastly, we will progressively build on top …

Add Q&A prep exercise Week 1

---

Week2/QA_PREP_EXERCISE.md
Week2/recipes.md

Hi all,
I wrote down what  I had in mind for week 2.
I tried to include some practice queries for joins but I was not sure how to properly ask this, given that they will create their own mock data.
Also, I couldn't really link the exercise to next week's material. Any ideas on how to make them think already about that (injections, transactions etc)?
Finally, I included here the exercise for the ERD. 
Let me know what you think :)

Preparatory Exercise for W2

---

Week3/QA_PREP_EXERCISES.md

Very short exercise but mainly added to initiate some discussion during the class.
This can be refined for the future class(es)

add prep exercise for week 3

---

Week2/QA_PREP_EXERCISE.md

[Prep exercise week 2](https://github.com/HackYourFuture/databases/blob/master/Week2/QA_PREP_EXERCISE.md) aka QA_PREP_EXERCISE.md has a block-quote:
> All the vegetarian recipes with potatoes All the cakes that do not need baking All the vegan and Japanese recipes
Replace it with a bullet list.

Replace block-quote with bullet list in "Prep exercise week 2"

---

Week2/QA_PREP_EXERCISE.md

fixed lucidchart link
fixed drawio link

Corrected broken URL in databasew2 prepexw2
